name: Testing

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        resolver:
          - lts-18 # ghc 8.10
          - lts-19 # ghc 9.0
          - lts-20 # ghc 9.2
          - lts-21 # ghc 9.4
          - lts-22 # ghc 9.6
          - nightly # ghc 9.8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8'
          cabal-version: '3.12.1.0'

      - uses: actions/cache@v4
        env:
          cache-name: cache-stack
        with:
          path: |
            .stack-work
            ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.resolver }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup
        run: stack setup --resolver ${{ matrix.resolver }}

      - name: Build library
        run: stack build --resolver ${{ matrix.resolver }}

      - name: Build examples
        # Disabled with the 2 olderst resolvers, because they require too many extra-deps
        if: matrix.resolver != 'lts-18' && matrix.resolver != 'lts-19'
        run: stack build --flag oidc-client:build-examples --resolver ${{ matrix.resolver }}

      - name: Run tests
        run: stack test --resolver ${{ matrix.resolver }}
